name: compose

services:
  ui:
    build: .
    environment:
      - NODE_ENV=development
      - DENO_NO_UPDATE_CHECK=1
      - TINI_SUBREAPER=1
    init: true
    ports:
      - "${UI_PORT:-5177}:5173"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - app.d.ts
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./deno.json
        - action: rebuild
          path: ./deno.lock
        - action: rebuild
          path: ./Dockerfile
